import { ok, withApi } from "../../../server/http.js";

export default withApi((request) => ok(request, {
  protocol: "current-cofi-agent-tools",
  version: "1.12.0",
  network: "ARC-TESTNET",
  mcp: {
    package: "@currentcofi/mcp",
    version: "0.1.0",
    transport: "stdio",
    manifest: "/api/v1/mcp-manifest",
    defaultMode: "read-only",
    writeBoundary: "Project mode, scoped credentials, exact approval phrases, HMAC signatures, and Current policy evaluation are required.",
  },
  authentication: {
    type: "scoped-api-key",
    signature: "HMAC-SHA256",
    timestampHeader: "x-current-timestamp",
    signatureHeader: "x-current-signature",
  },
  tools: [
    {
      name: "propose_programmable_checkout",
      description: "Propose a walletless USDC checkout with policy-bounded affiliate payouts and customer rewards. Link creation never moves customer funds.",
      method: "POST",
      path: "/api/v1/developer/agent-actions",
      permission: "agent-actions:write",
      input: { kind: "programmable_checkout", idempotencyKey: "stable unique action identifier", title: "checkout title", amount: "decimal USDC price", splits: "optional affiliate and customer-reward destinations" },
      outcomes: { completed: "Policy passed and the hosted checkout link was created; no customer funds moved.", approval_required: "Paused in the human approval queue.", blocked: "Rejected by agent checkout limits." },
    },
    {
      name: "create_usdc_subscription_plan",
      description: "Publish a walletless recurring USDC plan with explicit subscriber approval for every Arc settlement cycle.",
      method: "POST",
      path: "/api/v1/developer/subscriptions",
      permission: "campaigns:write",
      input: { title: "plan title", description: "optional description", amount: "decimal USDC amount", intervalDays: "7 | 30 | 90 | 365", successUrl: "optional http or https redirect" },
    },
    {
      name: "read_usdc_subscription_activity",
      description: "Read plans, subscriber periods, renewal readiness, confirmed cycles, and recurring USDC volume.",
      method: "GET",
      path: "/api/v1/developer/subscriptions",
      permission: "analytics:read",
    },
    {
      name: "create_usdc_checkout",
      description: "Publish a fixed-price hosted USDC checkout that onboards walletless customers and settles directly to the merchant's Arc wallet.",
      method: "POST",
      path: "/api/v1/developer/checkout",
      permission: "campaigns:write",
      input: {
        title: "product or payment title",
        description: "optional customer-facing description",
        amount: "decimal USDC amount",
        expiresInHours: "optional 1-720",
        successUrl: "optional http or https redirect",
      },
    },
    {
      name: "read_usdc_checkout_activity",
      description: "Read checkout links, direct Arc settlements, receipts, refunds, and merchant volume.",
      method: "GET",
      path: "/api/v1/developer/checkout",
      permission: "analytics:read",
    },
    {
      name: "prepare_milestone_escrow",
      description: "Prepare a fully funded USDC or Arc project-token agreement with sequential proof, release, dispute, and recovery boundaries. An authorized client wallet completes funding.",
      method: "POST",
      path: "/api/v1/developer/escrow",
      permission: "campaigns:write",
      input: {
        name: "string",
        clientAddress: "authorized Arc wallet",
        providerAddress: "service-provider Arc wallet",
        arbitratorAddress: "independent Arc wallet",
        tokenAddress: "optional Arc ERC-20 address; omit for USDC",
        milestones: "array of { title, amount, dueAt }",
      },
    },
    {
      name: "read_milestone_escrow",
      description: "Read agreement funding, active milestone, proof, release, dispute, refund, and cancellation state.",
      method: "GET",
      path: "/api/v1/developer/escrow",
      permission: "analytics:read",
    },
    {
      name: "propose_reward_distribution",
      description: "Propose a walletless USDC or project-token campaign through enforced reward, identity, daily-volume, and human-approval policies.",
      method: "POST",
      path: "/api/v1/developer/agent-actions",
      permission: "agent-actions:write",
      input: {
        idempotencyKey: "stable unique action identifier",
        name: "string",
        tokenAddress: "optional Arc ERC-20 address; omit for USDC",
        recipients: "array of { identityType, identity, amount }",
        expiresInHours: "1-720",
        activationEvent: "optional project event type",
        referralReward: "optional project-defined reward label",
      },
      outcomes: {
        awaiting_settlement: "Policy approved, the campaign was created, and an authorized project wallet must approve the token and fund the Arc vault.",
        completed: "The campaign vault funding transaction was confirmed on Arc.",
        approval_required: "Paused in the workspace approval queue.",
        blocked: "Rejected by the agent's configured boundaries.",
      },
    },
    {
      name: "read_agent_settlement",
      description: "Read policy, human-review, token-approval, Arc-vault funding, and transaction-proof state for agent proposals.",
      method: "GET",
      path: "/api/v1/developer/agent-actions",
      permission: "agent-actions:read",
      outcomes: {
        awaiting_settlement: "Campaign exists but funds have not moved into the Arc vault.",
        completed: "Arc vault funding is confirmed and includes a transaction receipt.",
      },
    },
    {
      name: "create_distribution",
      description: "Create a funded-wallet onboarding campaign for USDC or an Arc project token.",
      method: "POST",
      path: "/api/v1/developer/distributions",
      permission: "campaigns:write",
      input: {
        name: "string",
        tokenAddress: "optional Arc ERC-20 address; omit for USDC",
        recipients: "array of { identityType, identity, amount }",
        expiresInHours: "1-720",
        activationEvent: "optional project event type",
        referralReward: "optional project-defined reward label",
      },
    },
    {
      name: "attest_identity",
      description: "Bind a project-verified X, game, or custom identity to the recipient's Current Arc wallet.",
      method: "POST",
      path: "/api/v1/developer/identity-attestations",
      permission: "identities:write",
      input: {
        externalEventId: "stable project verification identifier",
        distributionId: "uuid",
        identityType: "x | game | custom",
        identity: "project-verified account identifier",
        walletAddress: "recipient Current Arc wallet",
        provider: "optional verifier name",
        expiresInMinutes: "5-1440",
      },
    },
    {
      name: "submit_activation",
      description: "Submit a verified post-claim activation for attribution and webhook delivery.",
      method: "POST",
      path: "/api/v1/developer/activations",
      permission: "activations:write",
      input: {
        externalEventId: "string",
        eventType: "string",
        distributionId: "uuid",
        walletAddress: "0x address",
        occurredAt: "ISO-8601",
        payload: "object",
      },
    },
    {
      name: "campaign_analytics",
      description: "Read campaign, recipient, claim, and activation totals.",
      method: "GET",
      path: "/api/v1/developer/analytics",
      permission: "analytics:read",
    },
    {
      name: "campaign_quality",
      description: "Read explainable participant-risk signals, referral-review queues, and age-eligible retention cohorts without blocking claims.",
      method: "GET",
      path: "/api/v1/developer/quality",
      permission: "analytics:read",
    },
    {
      name: "evaluate_campaign_quality",
      description: "Evaluate one campaign under its configured quality policy and emit auditable, explainable decisions.",
      method: "POST",
      path: "/api/v1/developer/quality",
      permission: "campaigns:write",
      input: {
        action: "evaluate",
        distributionId: "campaign uuid",
      },
    },
    {
      name: "create_pilot",
      description: "Open a measurable external-project pilot with targets, integrations, and a partner attestation path.",
      method: "POST",
      path: "/api/v1/developer/pilots",
      permission: "pilots:write",
      input: {
        partnerName: "string",
        partnerWebsite: "optional URL",
        useCase: "string",
        integrationMode: "hosted-links | react-embed | server-sdk | agent-api",
        targetRecipients: "integer",
        targetClaimRate: "0-100",
        targetActivationRate: "0-100",
        requestedIntegrations: "array",
        dueAt: "optional ISO-8601 date",
      },
    },
    {
      name: "create_grant_evidence",
      description: "Freeze campaign, settlement, wallet, identity, activation, and integration proof into a shareable report.",
      method: "POST",
      path: "/api/v1/developer/evidence",
      permission: "evidence:write",
      input: {
        distributionId: "optional campaign uuid; omit for the complete project",
      },
    },
    {
      name: "create_grant_review",
      description: "Create a public Circle reviewer room mapping immutable product evidence to platform alignment, traction, ecosystem impact, security gaps, and measurable milestones.",
      method: "POST",
      path: "/api/v1/developer/grant",
      permission: "evidence:write",
      input: {
        distributionId: "optional campaign uuid; omit for the complete project",
      },
    },
    {
      name: "current_economy",
      description: "Read verifiable $CURRENT supply, access tiers, product fees, and governed buyback execution.",
      method: "GET",
      path: "/api/v1/token/economy",
      permission: "public",
    },
  ],
}), ["GET"]);
