import { ok, withApi } from "../../../server/http.js";

export default withApi((request) => ok(request, {
  protocol: "current-cofi-agent-tools",
  version: "1.7.0",
  network: "ARC-TESTNET",
  authentication: {
    type: "scoped-api-key",
    signature: "HMAC-SHA256",
    timestampHeader: "x-current-timestamp",
    signatureHeader: "x-current-signature",
  },
  tools: [
    {
      name: "prepare_milestone_escrow",
      description: "Prepare a fully funded USDC or Arc project-token agreement with sequential proof, release, dispute, and recovery boundaries. An authorized client wallet completes funding.",
      method: "POST",
      path: "/api/v1/developer/escrow",
      permission: "campaigns:write",
      input: {
        name: "string",
        clientAddress: "authorized Arc wallet",
        providerAddress: "service-provider Arc wallet",
        arbitratorAddress: "independent Arc wallet",
        tokenAddress: "optional Arc ERC-20 address; omit for USDC",
        milestones: "array of { title, amount, dueAt }",
      },
    },
    {
      name: "read_milestone_escrow",
      description: "Read agreement funding, active milestone, proof, release, dispute, refund, and cancellation state.",
      method: "GET",
      path: "/api/v1/developer/escrow",
      permission: "analytics:read",
    },
    {
      name: "propose_reward_distribution",
      description: "Propose a walletless USDC or project-token campaign through enforced reward, identity, daily-volume, and human-approval policies.",
      method: "POST",
      path: "/api/v1/developer/agent-actions",
      permission: "agent-actions:write",
      input: {
        idempotencyKey: "stable unique action identifier",
        name: "string",
        tokenAddress: "optional Arc ERC-20 address; omit for USDC",
        recipients: "array of { identityType, identity, amount }",
        expiresInHours: "1-720",
        activationEvent: "optional project event type",
        referralReward: "optional project-defined reward label",
      },
      outcomes: {
        awaiting_settlement: "Policy approved, the campaign was created, and an authorized project wallet must approve the token and fund the Arc vault.",
        completed: "The campaign vault funding transaction was confirmed on Arc.",
        approval_required: "Paused in the workspace approval queue.",
        blocked: "Rejected by the agent's configured boundaries.",
      },
    },
    {
      name: "read_agent_settlement",
      description: "Read policy, human-review, token-approval, Arc-vault funding, and transaction-proof state for agent proposals.",
      method: "GET",
      path: "/api/v1/developer/agent-actions",
      permission: "agent-actions:read",
      outcomes: {
        awaiting_settlement: "Campaign exists but funds have not moved into the Arc vault.",
        completed: "Arc vault funding is confirmed and includes a transaction receipt.",
      },
    },
    {
      name: "create_distribution",
      description: "Create a funded-wallet onboarding campaign for USDC or an Arc project token.",
      method: "POST",
      path: "/api/v1/developer/distributions",
      permission: "campaigns:write",
      input: {
        name: "string",
        tokenAddress: "optional Arc ERC-20 address; omit for USDC",
        recipients: "array of { identityType, identity, amount }",
        expiresInHours: "1-720",
        activationEvent: "optional project event type",
        referralReward: "optional project-defined reward label",
      },
    },
    {
      name: "attest_identity",
      description: "Bind a project-verified X, game, or custom identity to the recipient's Current Arc wallet.",
      method: "POST",
      path: "/api/v1/developer/identity-attestations",
      permission: "identities:write",
      input: {
        externalEventId: "stable project verification identifier",
        distributionId: "uuid",
        identityType: "x | game | custom",
        identity: "project-verified account identifier",
        walletAddress: "recipient Current Arc wallet",
        provider: "optional verifier name",
        expiresInMinutes: "5-1440",
      },
    },
    {
      name: "submit_activation",
      description: "Submit a verified post-claim activation for attribution and webhook delivery.",
      method: "POST",
      path: "/api/v1/developer/activations",
      permission: "activations:write",
      input: {
        externalEventId: "string",
        eventType: "string",
        distributionId: "uuid",
        walletAddress: "0x address",
        occurredAt: "ISO-8601",
        payload: "object",
      },
    },
    {
      name: "campaign_analytics",
      description: "Read campaign, recipient, claim, and activation totals.",
      method: "GET",
      path: "/api/v1/developer/analytics",
      permission: "analytics:read",
    },
    {
      name: "campaign_quality",
      description: "Read explainable participant-risk signals, referral-review queues, and age-eligible retention cohorts without blocking claims.",
      method: "GET",
      path: "/api/v1/developer/quality",
      permission: "analytics:read",
    },
    {
      name: "evaluate_campaign_quality",
      description: "Evaluate one campaign under its configured quality policy and emit auditable, explainable decisions.",
      method: "POST",
      path: "/api/v1/developer/quality",
      permission: "campaigns:write",
      input: {
        action: "evaluate",
        distributionId: "campaign uuid",
      },
    },
    {
      name: "create_pilot",
      description: "Open a measurable external-project pilot with targets, integrations, and a partner attestation path.",
      method: "POST",
      path: "/api/v1/developer/pilots",
      permission: "pilots:write",
      input: {
        partnerName: "string",
        partnerWebsite: "optional URL",
        useCase: "string",
        integrationMode: "hosted-links | react-embed | server-sdk | agent-api",
        targetRecipients: "integer",
        targetClaimRate: "0-100",
        targetActivationRate: "0-100",
        requestedIntegrations: "array",
        dueAt: "optional ISO-8601 date",
      },
    },
    {
      name: "create_grant_evidence",
      description: "Freeze campaign, settlement, wallet, identity, activation, and integration proof into a shareable report.",
      method: "POST",
      path: "/api/v1/developer/evidence",
      permission: "evidence:write",
      input: {
        distributionId: "optional campaign uuid; omit for the complete project",
      },
    },
    {
      name: "current_economy",
      description: "Read verifiable $CURRENT supply, access tiers, product fees, and governed buyback execution.",
      method: "GET",
      path: "/api/v1/token/economy",
      permission: "public",
    },
  ],
}), ["GET"]);
